### ISSUE TITLE
php script in repo 

### ISSUE THREAD

**Issue by MatthiasLiszt** [dervondenbergen/test-web-counter#1]
Would be interesting to see the source of the php script once again ... 

Thanks for the life coding !

**Comment by dervondenbergen** [comment]
Die PHP Datei ist jetzt auch im Repo: [count.php](https://github.com/dervondenbergen/test-web-counter/blob/master/count.php)

Zu bedenken ist, dass das GitHub Repo am server auch einen Token beinhalten muss, damit die pushes funktionieren. Den kann man hier erstellen https://github.com/settings/tokens

**Comment by MatthiasLiszt** [comment]
Thanks! There are just a lot of small things which make a great repo.

**Comment by dervondenbergen** [comment]
Closing this issue, as it looks like the problem is solved 😄
